# Generated by Django 5.0.6 on 2024-07-22 15:08

import apps.news.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('category', models.CharField(max_length=100, verbose_name='Categoría')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('image', models.ImageField(upload_to='news/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp']), apps.news.models.validateImageSize], verbose_name='Imagen')),
                ('autor', models.CharField(default='Anónimo', max_length=100, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'New',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.new', verbose_name='Noticia')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
