# Generated by Django 5.0.6 on 2024-07-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='check_comment',
            field=models.BooleanField(default=False, verbose_name='Aprobada'),
        ),
    ]
