# Generated by Django 5.0.6 on 2024-07-22 15:10

import apps.users.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre')),
                ('lastname', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellidos')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp']), apps.users.models.validateImageSize], verbose_name='Imagen de Perfil')),
                ('user_active', models.BooleanField(default=True)),
                ('user_administrator', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
