# Generated by Django 5.0.6 on 2024-08-02 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userp_groups_userp_is_superuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userp',
            old_name='user_active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='userp',
            old_name='user_administrator',
            new_name='is_staff',
        ),
    ]
