# Generated by Django 5.0.6 on 2024-07-28 20:50

import apps.team.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('job', models.CharField(max_length=100, verbose_name='Cargo')),
                ('imagen', models.ImageField(upload_to='team/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp']), apps.team.models.validateImageSize], verbose_name='Imagen')),
                ('facebook', models.URLField(verbose_name='Facebook')),
                ('twitter', models.URLField(verbose_name='Twitter')),
                ('instagram', models.URLField(verbose_name='Instagram')),
                ('google', models.URLField(verbose_name='Google+')),
                ('linkedin', models.URLField(verbose_name='Linked In')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
    ]
