# Generated by Django 5.0.6 on 2024-07-28 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='imagen',
            new_name='image',
        ),
    ]
